### ISSUE TITLE
Oprava domácího úkolu

### ISSUE THREAD

**Issue by lrolecek** [intie/zivotopis#2]
Ahoj druhý Luďku,

koukám na tvůj úkol a vidím tam pár drobných chyb. Například:

1. Na řádku 68 v CSS máš napsáno `font-style: bold`, ale pokud chceš dělat tučné písmo, musíš použít vlastnost `font-weight: bold`. Vlastnost `font-style` je na nastavování kurzívy.

2. V HTML ti chybí uzavírací značka k divu, který začíná na řádku 12, ale nikde nekončí.

### Proveď opravy

Než ti úkol uznám jako odevzdaný, prosím proveď následující opravy:

- [x] v CSS nahraď špatně použité vlastnosti za ty správné
- [x] v HTML uzavři všechny značky, aby byl kód validní
- [x] naformátuj HTML a CSS, aby bylo hezky zarovnané

**Comment by intie** [comment]
Ahoj Luďku, děkuju za zpětnou vazbu. Vše je opraveno.

**Comment by lrolecek** [comment]
Ok, díky. Úkol uznávám jako odevzdaný. Dobrá práce.
